name: Set up Node.js and Yarn
description: Set up Node.js and Yarn, then install package dependencies.
author: LayZeeDK

runs:
  using: composite
  steps:
    - name: Set up Node.js and Yarn
      uses: actions/setup-node@v4
      with:
        node-version-file: .node-version
        cache: yarn
    - name: Install package dependencies
      run: yarn install --frozen-lockfile --no-interactive
      shell: bash
